title: "Project T"
author: "Fabio"
date: "`r Sys.Date()`"
output:
  ioslides_presentation: default
  beamer_presentation: default  Fabio Massimo Lattanzio
  slidy_presentation: default
  powerpoint_presentation: default

## Grafici

str(Magazzino)
str(Fatturato)
summary(Magazzino)
summary(Fatturato)

ggplot(TotSum, aes(x=Mese_Anno)) + 
  geom_line(aes(y = Fatturato), color = "darkred") + 
  geom_line(aes(y = Q.tà), color = "steelblue")

summary(Accessori)
summary(Audio)
summary(Libri)
summary(Liuteria)
summary(Strumenti)

par(mfrow=c(1,3))
boxplot(Fatturato$Importo,ylab="Euro", main="Importo")
boxplot(Fatturato$Prezzo,ylab="Euro", main="Prezzo")
boxplot(Fatturato$Q.tà,ylab="N°Articoli", main="Q.tà")
 
par(mfrow=c(1,2))
hist(Fatturato$Q.tà, main="Istogramma Q.tà", xlab="N°Articoli per Vendita", ylab="N°Vendite")
qqnorm(Fatturato$Q.tà, main="Q-Q Plot Q.tà", ylab="N°Articoli per Vendità", xlab="Quantili")

par(mfrow=c(1,2))
hist(Fatturato$Importo, main="Istogramma Importo",ylab="N°Vendite", xlab="Importo per Vendità in Euro")
qqnorm(Fatturato$Importo, main="Q-Q Plot Importo", ylab="Importo per Vendità in Euro", xlab="Quantili")

plot(Fatturato$Mese_Anno, Fatturato$Importo, 
      xlab="Mesi", ylab="Importo", main="Importo per Vendita Mensile")
      
ggplot(data = TotSum, aes(x = Mese_Anno, y = Q.tà)) +
  geom_line() + ggtitle("Quantità articoli venduti per mese nel periodo di osservazione") +
  xlab("Mesi") + ylab("N°Articoli")

ggplot(data = TotSum, aes(x = Mese_Anno, y = Fatturato)) +
  geom_line() + ggtitle("Importi  articoli venduti per mese nel periodo di osservazione") +
  xlab("Mesi") + ylab("Importo in Euro")

ggplot(data = TotSum, aes(x = Mese_Anno, y = Fatturato)) + 
   geom_area() + ggtitle("Importi  articoli venduti per mese nel periodo di osservazione") + 
   xlab("Mesi") + ylab("Importo in Euro") 

ggplot(TotSum, aes(x=Mese_Anno)) +  
  geom_line(aes(y = Fatturato), color = "blueviolet") +  
  geom_line(aes(y = Q.tà), color = "chartreuse")

ggplot(CattPezz, aes(x=Mese_Anno)) +
  geom_line(aes(y = LIBRI), color = "cyan") +
  geom_line(aes(y = STRUMENTI_MUSICALI), color ="darkgreen") + 
  ggtitle("Confronto tra Libri e Strumenti Musicali in N°Articoli") + 
   xlab("Mesi") + ylab("N°Articoli")
  
ggplot(CattPezz, aes(x=Mese_Anno)) +
  geom_line(aes(y = ACCESSORI), color = "darkred") + 
  geom_line(aes(y = STRUMENTI_MUSICALI), color ="darkgreen") + 
  ggtitle("Confronto tra Accessori e Strumenti Musicali in N°Articoli") + 
   xlab("Mesi") + ylab("N°Articoli")

ggplot(CattPezz, aes(x=Mese_Anno)) +
  geom_line(aes(y = LIUTERIA), color = "chocolate1") +
  geom_line(aes(y = STRUMENTI_MUSICALI), color ="darkgreen") + 
  ggtitle("Confronto tra Liuteria e Strumenti Musicali in N°Articoli") + 
   xlab("Mesi") + ylab("N°Articoli")

ggplot(CattPezz, aes(x=Mese_Anno)) +
  geom_line(aes(y = ACCESSORI), color = "darkred") +
  geom_line(aes(y = LIUTERIA), color = "chocolate1") + 
  ggtitle("Confronto tra Accessori e Liuteria in N°Articoli") + 
   xlab("Mesi") + ylab("N°Articoli")

ggplot(CattPezz, aes(x=Mese_Anno)) + 
  geom_line(aes(y = ACCESSORI), color = "darkred") + 
  geom_line(aes(y = AUDIO), color = "steelblue") +
  geom_line(aes(y = LIBRI), color = "cyan") +
  geom_line(aes(y = LIUTERIA), color = "chocolate1") +
  geom_line(aes(y = STRUMENTI_MUSICALI), color ="darkgreen") + 
  ggtitle("Quantità vendite distinto per serie") + 
   xlab("Mesi") + ylab("N°Articoli")
   
ggplot(FattCatt, aes(x=Mese_Anno)) + 
  geom_line(aes(y = ACCESSORI), color = "darkred") + 
  geom_line(aes(y = AUDIO), color = "steelblue") +
  geom_line(aes(y = LIBRI), color = "cyan") +
  geom_line(aes(y = LIUTERIA), color = "chocolate1") +
  geom_line(aes(y = STRUMENTI_MUSICALI), color ="darkgreen") + 
  ggtitle("Importo vendite distinto per serie") + 
   xlab("Mesi") + ylab("Importo in Euro") 

data(Fatturato)   
plot(data = Fatturato, Importo ~ Mese_Anno, ylab = "Importo", xlab="Mesi", main="Trand Andamento Negozio")
abline(lm(data = Fatturato, Importo ~ Mese_Anno), col = "red")






